# Generated by Django 4.0.3 on 2022-05-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipelist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
