# Generated by Django 4.0.3 on 2022-06-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipelist_app', '0002_dish_type_alter_ingredient_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.CharField(max_length=200)),
                ('time_or_not', models.BooleanField()),
                ('time', models.IntegerField(default=0)),
                ('id_support', models.IntegerField(default=0)),
            ],
        ),
    ]
