# Generated by Django 4.0.3 on 2022-06-03 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipelist_app', '0004_rename_instructions_recipe_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=255)),
                ('time', models.IntegerField(default=0)),
                ('support_id', models.IntegerField(blank=True, null=True)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipelist_app.dish')),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
