# Generated by Django 4.0.3 on 2022-06-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipelist_app', '0006_rename_recipes_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='step_number',
            field=models.IntegerField(null=True),
        ),
    ]
