# Generated by Django 4.0.3 on 2022-06-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipelist_app', '0008_alter_recipe_step_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='step_number',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='support_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
